site: github.com
language: 日本語
description: GitHub UIの日本語翻訳
version: 0.6.0
author: 223n
last_updated: '2025-03-09'
translations:
  - original: Pull requests
    translated: プルリクエスト
    context: メインナビゲーション
  - original: Issues
    translated: 課題
    context: メインナビゲーション
  - original: Marketplace
    translated: マーケットプレイス
    context: メインナビゲーション
  - original: Explore
    translated: 探索
    context: メインナビゲーション
  - original: Code
    translated: コード
    context: リポジトリタブ
  - original: Pull requests
    translated: プルリクエスト
    context: リポジトリタブ
  - original: Actions
    translated: アクション
    context: リポジトリタブ
  - original: Projects
    translated: プロジェクト
    context: リポジトリタブ
  - original: Wiki
    translated: ウィキ
    context: リポジトリタブ
  - original: Security
    translated: セキュリティ
    context: リポジトリタブ
  - original: Insights
    translated: インサイト
    context: リポジトリタブ
  - original: Settings
    translated: 設定
    context: リポジトリタブ
  - original: Workflows
    translated: ワークフロー
    context: アクションタブ
  - original: Runs
    translated: 実行履歴
    context: アクションタブ
  - original: Projects (classic)
    translated: プロジェクト(クラシック)
    context: プロジェクトタブ
  - original: Projects (beta)
    translated: プロジェクト(ベータ)
    context: プロジェクトタブ
  - original: Overview
    translated: 概要
    context: プロフィール
  - original: Repositories
    translated: リポジトリー
    context: プロフィール
  - original: Projects
    translated: プロジェクト
    context: プロフィール
  - original: Packages
    translated: パッケージ
    context: プロフィール
  - original: Stars
    translated: お気に入り
    context: プロフィール
  - original: Followers
    translated: フォロワー
    context: プロフィール
  - original: Following
    translated: フォロー中
    context: プロフィール
  - original: New
    translated: 新規
    context: ボタン
  - original: Create
    translated: 作成
    context: ボタン
  - original: Delete
    translated: 削除
    context: ボタン
  - original: Edit
    translated: 編集
    context: ボタン
  - original: Save
    translated: 保存
    context: ボタン
  - original: Cancel
    translated: キャンセル
    context: ボタン
  - original: Fork
    translated: フォーク
    context: ボタン
  - original: Star
    translated: お気に入り
    context: ボタン
  - original: Watch
    translated: ウォッチ
    context: ボタン
  - original: Edit profile
    translated: プロフィールを編集
    context: ボタン
  - original: Actions
    translated: アクション
    context: 特殊要素
  - original: Projects
    translated: プロジェクト
    context: 特殊要素
  - original: ' Actions'
    translated: アクション
    context: 特殊要素
  - original: ' Projects'
    translated: プロジェクト
    context: 特殊要素
  - original: Achievements
    translated: 実績
    context: 特殊要素
  - original: Contribution activity
    translated: 貢献活動
    context: 特殊要素
  - original: 'Issue #(\d+)'
    translated: '課題 #$1'
    context: 課題表示
    regex: true
  - original: (\d+) commits?
    translated: $1 コミット
    context: コミット数
    regex: true
  - original: (\d+) contributions? in the last year
    translated: '昨年の貢献数: $1'
    context: プロフィールページ
    regex: true
  - original: ([A-Za-z0-9_-]+)/([A-Za-z0-9_-]+)#(\d+)
    translated: $1/$2 課題#$3
    context: 課題リファレンス
    regex: true
  - original: Created (\d+) days? ago
    translated: $1 日前に作成
    context: 日時表示
    regex: true
  - original: Last updated (\w+ \d+, \d+)
    translated: '最終更新: $1'
    context: 日時表示
    regex: true
  - original: Copy path
    translated: パスをコピー
    context: ファイルメニュー
  - original: Copy permalink
    translated: 永続リンクをコピー
    context: ファイルメニュー
  - original: Show more activity
    translated: さらに表示
    context: ボタン
  - original: Learn more
    translated: 詳細を見る
    context: ボタン
  - original: Sort
    translated: 並び順
    context: ボタン
  - original: Create list
    translated: リストを作成
    context: ボタン
  - original: Lists
    translated: リスト
    context: 特殊要素
  - original: Starred
    translated: お気に入り追加済み
    context: ボタン
  - original: Loading
    translated: 読み込み中
    context: ボタン
  - original: Seeing something unexpected?
    translated: 予期しない出来事が発生しましたか？
    context: ラベル
  - original: Take a look at the
    translated: こちらをご覧ください
    context: ラベル
  - original: New Issue
    translated: 新しい課題
    context: ボタン
  - original: Labels
    translated: ラベル
    context: ボタン
  - original: New Label
    translated: 新しいラベル
    context: ボタン
  - original: (\d+) labels
    translated: ラベル数：$1
    context: ラベル
    regex: true
  - original: Milestones
    translated: マイルストーン
    context: ボタン
  - original: Search all labels
    translated: すべてのラベルから検索
    context: 文字列
  - original: Filters
    translated: フィルター
    context: コンボボックス
  - original: Author
    translated: 作成者
    context: 検索条件
  - original: Label
    translated: ラベル
    context: 検索条件
  - original: Assignee
    translated: 担当者
    context: 検索条件
  - original: There aren’t any open pull requests.
    translated: 開かれているプルリクエストはありません。
    context: 文字列
  - original: (\d+) Open
    translated: 開かれている（$1件）
    context: プルリクエスト
    regex: true
  - original: (\d+) Closed
    translated: 閉じられている（$1件）
    context: プルリクエスト
    regex: true
  - original: (\d+) stars
    translated: $1 お気に入り
    context: コード
    regex: true
  - original: (\d+) forks
    translated: $1 フォーク
    context: コード
    regex: true
  - original: (\d+) watching
    translated: $1 ウォッチ
    context: コード
    regex: true
  - original: (\d+) Branch
    translated: $1 ブランチ
    context: コード
    regex: true
  - original: (\d+) Tags
    translated: $1 タグ
    context: コード
    regex: true
  - original: Activity
    translated: 活動状況
    context: コード
  - original: Public repository
    translated: 公開リポジトリー
    context: コード
  - original: Private repository
    translated: 非公開リポジトリー
    context: コード
